// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MortgageRate
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("rateType")]
        public string RateType { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("term")]
        public long? Term { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("country")]
        public string Country { get; set; }

        [JsonProperty("year")]
        public long? Year { get; set; }

        [JsonProperty("month")]
        public long? Month { get; set; }

        [JsonProperty("count")]
        public long? Count { get; set; }

        [JsonProperty("rates")]
        public Rate[] Rates { get; set; }

        [JsonProperty("change1w")]
        public double? Change1W { get; set; }

        [JsonProperty("changeDirection")]
        public string ChangeDirection { get; set; }

        [JsonProperty("previousRate")]
        public double? PreviousRate { get; set; }

        [JsonProperty("previousDate")]
        public DateTimeOffset? PreviousDate { get; set; }
    }

    public partial class Rate
    {
        [JsonProperty("week")]
        public DateTimeOffset? Week { get; set; }

        [JsonProperty("rate")]
        public double? RateRate { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
